name: ship-traj-mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # or 3.11 / 3.12
  - pip
  - numpy
  - pandas
  - h5py
  - scikit-learn
  - matplotlib
  - tqdm
  - requests
  - pip:
    - tensorflow>=2.10
    - keras-tuner
    - mlflow>=2.10
    - gradio>=4.0
    - joblib
