name: ship-traj-mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - h5py
  - scikit-learn
  - matplotlib
  - tqdm
  - pyyaml
  # PyTorch Dependencies
  - pytorch
  - torchvision
  - cpuonly  # Remove this if you have a GPU
  - pip:
    - mlflow>=2.10
    - gradio>=4.0
    - joblib
